# Initialization
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

# Environment Variables
environment:
  MYGET_API_KEY:
    secure: 0nbVWbM2QiMez3A6xrHXF3KnFQ95AD7xOX4FPcifqipsyjiDBbjrKrMEM5/U+qtt
  MYGET_SOURCE: https://www.myget.org/F/yvschmid/
  
# Cache
cache:
- src\packages -> src\**\packages.config
- tools -> tools\packages.config